version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
  tf: ngs/terraform@0.0.1
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: echo "cli setup is done"
workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
  tf:
    jobs:
      - tf/validate:
          name: validate
      - tf/plan:
          name: plan
          requires:
            - validate
      - tf/apply:
          name: apply
          requires:
            - plan
          filters:
            branches:
              only: master
